:::{.callout-tip collapse="true" icon=false}
## Le fichier `.gitignore`

::: {.incremental}
Lors de la création du projet via GitLab, aucun `.gitignore` n'a été créé à la racine du projet. Le `.gitignore` a pour objectif d'indiquer à Git les fichiers ou les types de fichiers dont les modifications seront à ignorer dans les futures commandes.

1. Créer un fichier ".gitignore" à la racine du projet.
2. Ajouter le contenu du [.gitignore standard R](https://github.com/github/gitignore/blob/main/R.gitignore)
3. Exclure également les fichiers de type `*.pdf` et `*.html`
4. Créer un dossier `data` à la racine du projet et à l'intérieur de celui-ci un fichier `data/raw.csv` 
5. Ajouter au `.gitignore`: `data/`
6. Effectuer un *commit* pour ajouter le fichier `.gitignore` au projet Git
7. Vérifier que toutes les règles ajoutées précédemment fonctionnent comme attendu
:::

:::

. . .

❓ **Question** : que se passe-t-il lorsque l'on ajoute au `.gitignore` des fichiers qui ont déjà été *commit* sur le projet Git ?
